name: Testing with Postman
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Testing with Postman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.15.0'
          check-latest: true

      - name: Install Dependencies
        run: npm install -g newman newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        run: npm run newmanGithubAction

      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults